language: go

go:
 - 1.11.x
 - 1.12.x
 - stable

before_install:
  - go get github.com/mitchellh/gox
  
script:
  - sh ./go-check-format.sh
  - go vet $(go list ./... | grep -v /vendor/)
  - go test -v -race ./...
  - go build
  - sh ./gox-build.sh $TRAVIS_TAG
 
