language: go

go:
 - 1.x
 - 1.11.x
 - 1.12.x
 - master

before_install:
  - go get github.com/mitchellh/gox
  
script:
  - if [ -n $(gofmt -l | grep -v /vendor/) ] then gofmt -l | grep -v /vendor/; fi
  - go vet $(go list ./... | grep -v /vendor/)
  - go test -v -race ./...
  - go build
  - if [ "${LATEST}" = "true" ]; then sh ./gox-build.sh; fi
 
